/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/man2.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(()=> {
    if(props.dance === -1) {
      actions.dance.play();
    } else {
      actions.dance.stop();
    }
  }, [props.dance]);

  return (
    <group ref={group} {...props} dispose={null} scale={0.01} position={[0,-1,0]}>
      <group name="Scene">
        <group name="man">
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="arms" geometry={nodes.arms.geometry} material={materials['skin_TEX.001']} skeleton={nodes.arms.skeleton} />
          <skinnedMesh name="brows" geometry={nodes.brows.geometry} material={materials['eyebro.001']} skeleton={nodes.brows.skeleton} />
          <skinnedMesh name="hair002" geometry={nodes.hair002.geometry} material={materials['hair.002']} skeleton={nodes.hair002.skeleton} />
          <skinnedMesh name="hair_GEO" geometry={nodes.hair_GEO.geometry} material={materials['hair.003']} skeleton={nodes.hair_GEO.skeleton} />
          <skinnedMesh name="head" geometry={nodes.head.geometry} material={materials['skin_TEX.001']} skeleton={nodes.head.skeleton} />
          <skinnedMesh name="head001" geometry={nodes.head001.geometry} material={materials['eyebro.001']} skeleton={nodes.head001.skeleton} />
          <group name="L_eyeball_GEO">
            <skinnedMesh name="Mesh031" geometry={nodes.Mesh031.geometry} material={materials['eye_blinn.001']} skeleton={nodes.Mesh031.skeleton} />
            <skinnedMesh name="Mesh031_1" geometry={nodes.Mesh031_1.geometry} material={materials['MAT-EYE.001']} skeleton={nodes.Mesh031_1.skeleton} />
          </group>
          <skinnedMesh name="L_eyeHighlight_GEO" geometry={nodes.L_eyeHighlight_GEO.geometry} material={materials['eyeHighlight_Ss.001']} skeleton={nodes.L_eyeHighlight_GEO.skeleton} />
          <skinnedMesh name="L_pupil_GEO" geometry={nodes.L_pupil_GEO.geometry} material={materials['pupil_sS.001']} skeleton={nodes.L_pupil_GEO.skeleton} />
          <group name="lower_teeth">
            <skinnedMesh name="Mesh037" geometry={nodes.Mesh037.geometry} material={materials['blinn1SG3.001']} skeleton={nodes.Mesh037.skeleton} />
            <skinnedMesh name="Mesh037_1" geometry={nodes.Mesh037_1.geometry} material={materials['blinn7SG1.001']} skeleton={nodes.Mesh037_1.skeleton} />
          </group>
          <skinnedMesh name="pants" geometry={nodes.pants.geometry} material={materials['pants.001']} skeleton={nodes.pants.skeleton} />
          <group name="R_eyeball_GEO">
            <skinnedMesh name="Mesh034" geometry={nodes.Mesh034.geometry} material={materials['eye_blinn.001']} skeleton={nodes.Mesh034.skeleton} />
            <skinnedMesh name="Mesh034_1" geometry={nodes.Mesh034_1.geometry} material={materials['MAT-EYE.001']} skeleton={nodes.Mesh034_1.skeleton} />
          </group>
          <skinnedMesh name="R_eyeHighlight_GEO" geometry={nodes.R_eyeHighlight_GEO.geometry} material={materials['eyeHighlight_Ss.001']} skeleton={nodes.R_eyeHighlight_GEO.skeleton} />
          <skinnedMesh name="R_pupil_GEO" geometry={nodes.R_pupil_GEO.geometry} material={materials['pupil_sS.001']} skeleton={nodes.R_pupil_GEO.skeleton} />
          <skinnedMesh name="shirt" geometry={nodes.shirt.geometry} material={materials['shirt.001']} skeleton={nodes.shirt.skeleton} />
          <group name="shoes">
            <skinnedMesh name="Mesh030" geometry={nodes.Mesh030.geometry} material={materials['shoes_01.001']} skeleton={nodes.Mesh030.skeleton} />
            <skinnedMesh name="Mesh030_1" geometry={nodes.Mesh030_1.geometry} material={materials['shoes_02.001']} skeleton={nodes.Mesh030_1.skeleton} />
            <skinnedMesh name="Mesh030_2" geometry={nodes.Mesh030_2.geometry} material={materials['shoes_03.001']} skeleton={nodes.Mesh030_2.skeleton} />
          </group>
          <skinnedMesh name="tongue" geometry={nodes.tongue.geometry} material={materials['blinn7SG1.001']} skeleton={nodes.tongue.skeleton} />
          <group name="upper_teeth">
            <skinnedMesh name="Mesh039" geometry={nodes.Mesh039.geometry} material={materials['blinn1SG3.001']} skeleton={nodes.Mesh039.skeleton} />
            <skinnedMesh name="Mesh039_1" geometry={nodes.Mesh039_1.geometry} material={materials['blinn7SG1.001']} skeleton={nodes.Mesh039_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/man2.glb')
